(function(){
  "use strict";
  const TYPES={
    risk:{title:"Risk Heatmap",kicker:"SITUATIONAL RISK",description:"Ward-level risk concentration and severity.",legend:[["normal","Normal"],["watch","Watch"],["high","High"],["critical","Critical"]]},
    flood:{title:"Flood Exposure",kicker:"HYDROLOGICAL VIEW",description:"Water depth and rainfall exposure across wards.",legend:[["low","Low"],["watch","Elevated"],["high","Severe"],["critical","Extreme"]]},
    access:{title:"Accessibility",kicker:"MOBILITY VIEW",description:"Ward accessibility with restricted and blocked roads.",legend:[["good","Open"],["watch","Restricted"],["critical","Blocked"]]},
    network:{title:"Road Network",kicker:"NETWORK VIEW",description:"Actual OSM road geometry and inter-ward connectivity.",legend:[["good","Open"],["watch","Restricted"],["critical","Blocked"]]},
    response:{title:"Response Focus",kicker:"OPERATIONS VIEW",description:"Highest-risk wards and their surrounding road access.",legend:[["critical","Priority"],["watch","Watch"],["good","Available"]]}
  };
  const state={windows:new Map(),nextOffset:0,z:10000};
  const esc=v=>typeof escapeHTML==="function"?escapeHTML(String(v)):String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const runtime=()=>typeof DASHBOARD_RUNTIME!=="undefined"?DASHBOARD_RUNTIME:null;
  function data(){const r=runtime();if(r?.wards?.length&&r?.roads?.length)return{wards:r.wards,roads:r.roads};return window.realDashboardGeoCache?.wards?.length&&window.realDashboardGeoCache?.roads?.length?window.realDashboardGeoCache:null;}
  function assessments(){const r=runtime();return r?.assessments instanceof Map?r.assessments:(window.realDashboardAssessments instanceof Map?window.realDashboardAssessments:new Map());}
  function wardId(w){const x=w?.properties?.ward_id??w?.properties?.ward;return x==null?null:`W${x}`;}
  function collect(v,out){if(!Array.isArray(v))return;if(v.length>=2&&Number.isFinite(Number(v[0]))&&Number.isFinite(Number(v[1]))){out.push([+v[0],+v[1]]);return;}v.forEach(x=>collect(x,out));}
  function projectFor(d,w,h){const pts=[];d.roads.forEach(r=>collect(r.path,pts));d.wards.forEach(x=>collect(x.geometry?.coordinates,pts));if(!pts.length)return null;const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=20,sx=Math.max(maxX-minX,1e-6),sy=Math.max(maxY-minY,1e-6),scale=Math.min((w-pad*2)/sx,(h-pad*2)/sy),dw=sx*scale,dh=sy*scale,ox=(w-dw)/2,oy=(h-dh)/2;return(lon,lat)=>[ox+(+lon-minX)*scale,h-(oy+(+lat-minY)*scale)];}
  function geom(g,p){if(!g)return"";const line=c=>Array.isArray(c)&&c.length>1?c.map((x,i)=>{const q=p(x[0],x[1]);return`${i?"L":"M"}${q[0].toFixed(2)} ${q[1].toFixed(2)}`}).join(" "):"";const poly=r=>Array.isArray(r)?r.map(x=>{const d=line(x);return d?d+" Z":""}).filter(Boolean).join(" "):"";return g.type==="Polygon"?poly(g.coordinates):g.type==="MultiPolygon"?g.coordinates.map(poly).filter(Boolean).join(" "):"";}
  function centroid(g,p){const pts=[];collect(g?.coordinates,pts);if(!pts.length)return null;return p(pts.reduce((a,x)=>a+x[0],0)/pts.length,pts.reduce((a,x)=>a+x[1],0)/pts.length);}
  function level(a){return String(a?.risk_level||"normal").toLowerCase();}
  function factor(a,...keys){for(const k of keys){const n=Number(a?.factors?.[k]);if(Number.isFinite(n))return n;}return 0;}
  function cls(type,a,road){if(type==="risk"||type==="response")return level(a);if(type==="flood"){const w=factor(a,"water_depth_m","water"),r=factor(a,"rainfall_mm_per_hr","rainfall");return w>=2||r>=100?"critical":w>=1||r>=50?"high":w>0||r>0?"watch":"low";}if(type==="access"){const x=factor(a,"accessibility_percent");return x<35?"critical":x<70?"watch":"good";}if(road)return road.blocked?"critical":Number(road.accessibility_percent??100)<70?"watch":"good";return"good";}
  function makeSvg(type,d){const W=720,H=410,p=projectFor(d,W,H),as=assessments();if(!p)return null;const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.classList.add("map-studio-svg");svg.setAttribute("viewBox",`0 0 ${W} ${H}`);svg.setAttribute("preserveAspectRatio","xMidYMid meet");const ns=svg.namespaceURI,wards=document.createElementNS(ns,"g"),links=document.createElementNS(ns,"g"),roads=document.createElementNS(ns,"g"),markers=document.createElementNS(ns,"g");wards.classList.add("studio-ward-layer");links.classList.add("studio-zone-links");roads.classList.add("studio-road-layer");markers.classList.add("studio-marker-layer");const centers=new Map();d.wards.forEach(w=>{const id=wardId(w),pt=centroid(w.geometry,p);if(id&&pt)centers.set(id,pt);const path=geom(w.geometry,p);if(!id||!path)return;const n=document.createElementNS(ns,"path");n.classList.add("studio-ward",cls(type,as.get(id)));n.dataset.zoneId=id;n.setAttribute("d",path);wards.appendChild(n);});d.roads.forEach(r=>{if(!Array.isArray(r.path)||r.path.length<2)return;const n=document.createElementNS(ns,"path");n.classList.add("studio-road",cls(type,null,r));n.setAttribute("d",r.path.map((x,i)=>{const q=p(x[0],x[1]);return`${i?"L":"M"}${q[0].toFixed(2)} ${q[1].toFixed(2)}`}).join(" "));roads.appendChild(n);});const seen=new Set();d.roads.forEach(r=>{if(!centers.has(r.from_zone_id)||!centers.has(r.to_zone_id))return;const k=[r.from_zone_id,r.to_zone_id].sort().join("|");if(seen.has(k))return;seen.add(k);const a=centers.get(r.from_zone_id),b=centers.get(r.to_zone_id),n=document.createElementNS(ns,"line");n.classList.add("studio-zone-link",cls(type,as.get(r.from_zone_id),r));n.setAttribute("x1",a[0]);n.setAttribute("y1",a[1]);n.setAttribute("x2",b[0]);n.setAttribute("y2",b[1]);links.appendChild(n);});centers.forEach((pt,id)=>{const n=document.createElementNS(ns,"circle");n.classList.add("studio-marker",cls(type,as.get(id)));n.dataset.zoneId=id;n.setAttribute("cx",pt[0]);n.setAttribute("cy",pt[1]);n.setAttribute("r","3");markers.appendChild(n);});svg.append(wards,links,roads,markers);return svg;}
  function ensureStyle(){if(document.getElementById("final-map-studio-style"))return;const s=document.createElement("style");s.id="final-map-studio-style";s.textContent=`.map-studio-topbar .final-actions{display:flex!important;flex-direction:row!important;gap:6px!important;align-items:center}.final-actions button{border:1px solid rgba(127,150,184,.22);background:rgba(255,255,255,.035);color:#aebfd6;border-radius:8px;padding:8px 11px;font:700 10px/1 inherit;cursor:pointer}.final-actions button:hover{border-color:rgba(255,178,29,.65);color:#fff}.map-studio-window{min-height:360px}.map-studio-body{position:relative}.map-studio-svg{touch-action:none}.map-v-final-tooltip{position:absolute;z-index:20;min-width:190px;max-width:240px;padding:10px 11px;border:1px solid rgba(83,113,153,.45);border-radius:10px;background:rgba(7,12,20,.97);box-shadow:0 14px 34px rgba(0,0,0,.45);pointer-events:none;color:#dce8f7}.map-v-final-tooltip b{display:block;color:#fff;font-size:12px}.map-v-final-tooltip span{display:block;color:#8fa5c0;font-size:10px;margin-top:3px}.map-v-final-tooltip strong{display:block;color:#35d07f;font-size:11px;margin-top:8px}.studio-marker{cursor:pointer}.studio-marker.selected{stroke:#fff;stroke-width:1.8}.studio-marker.hovered{stroke:#fff;stroke-width:1.6}.studio-ward.hovered{filter:brightness(1.7)}.map-studio-loading{height:260px;display:grid;place-items:center;color:#8ba0bb;font-size:12px}.map-studio-error{height:260px;display:grid;place-items:center;text-align:center;color:#8ba0bb;padding:20px}.map-studio-error strong{color:#fff}.map-studio-window .studio-road{pointer-events:none}`;document.head.appendChild(s);}
  function host(){let h=document.querySelector(".map-studio-host");if(h)return h;h=document.createElement("div");h.className="map-studio-host";h.innerHTML=`<div class="map-studio-backdrop"></div><div class="map-studio-topbar"><div><span>LIVE GEOSPATIAL WORKSPACE</span><strong>Chennai Map Studio</strong></div><div class="final-actions"><button data-final="open">Open all</button><button data-final="tile">Tile</button><button data-final="stack">Stack</button><button data-final="close">Close workspace</button></div></div>`;document.body.appendChild(h);h.querySelector("[data-final=close]").onclick=close;h.querySelector(".map-studio-backdrop").onclick=close;h.querySelector("[data-final=open]").onclick=()=>Object.keys(TYPES).forEach(open);h.querySelector("[data-final=tile]").onclick=tile;h.querySelector("[data-final=stack]").onclick=stack;return h;}
  function tooltip(win,e,id){const a=assessments().get(id);if(!a)return;let t=win.querySelector(".map-v-final-tooltip");if(!t){t=document.createElement("div");t.className="map-v-final-tooltip";win.querySelector(".map-studio-body").appendChild(t);}const w=factor(a,"water_depth_m","water"),r=factor(a,"rainfall_mm_per_hr","rainfall"),ac=a.factors?.accessibility_percent!=null?Number(a.factors.accessibility_percent):Math.max(0,100-factor(a,"accessibility_risk"));t.innerHTML=`<b>${esc(id)} · ${esc(level(a).toUpperCase())}</b><span>Risk score ${Number(a.risk_score??0).toFixed(2)} / 100</span><strong>Water ${w.toFixed(2)} m · Rain ${r.toFixed(0)} mm/hr · Access ${ac.toFixed(0)}%</strong>`;const rct=win.getBoundingClientRect(),wth=t.offsetWidth||210,hth=t.offsetHeight||80;let x=e.clientX-rct.left+12,y=e.clientY-rct.top+12;x=Math.min(Math.max(8,x),Math.max(8,rct.width-wth-8));y=Math.min(Math.max(8,y),Math.max(8,rct.height-hth-8));t.style.left=x+"px";t.style.top=y+"px";t.hidden=false;}
  function bind(win){const svg=win.querySelector("svg");if(!svg||svg.dataset.finalBound)return;svg.dataset.finalBound="1";const body=win.querySelector(".map-studio-body");let box={...svg.viewBox.baseVal},drag=false,moved=false,last=[0,0];const fit=()=>{try{const b=svg.getBBox();if(b.width&&b.height){box={x:b.x-15,y:b.y-15,width:b.width+30,height:b.height+30};svg.setAttribute("viewBox",`${box.x} ${box.y} ${box.width} ${box.height}`);}}catch{}};const zoom=(f,x=null,y=null)=>{const w=Math.max(35,Math.min(1000,box.width*f)),h=Math.max(28,Math.min(700,box.height*f)),rx=x==null?.5:(x-box.x)/box.width,ry=y==null?.5:(y-box.y)/box.height;box={x:x==null?box.x+(box.width-w)/2:x-w*rx,y:y==null?box.y+(box.height-h)/2:y-h*ry,width:w,height:h};svg.setAttribute("viewBox",`${box.x} ${box.y} ${box.width} ${box.height}`)};const c=document.createElement("div");c.className="final-map-controls";c.innerHTML=`<button>+</button><button>−</button><button>⌖</button>`;c.style.cssText="position:absolute;right:14px;top:14px;z-index:12;display:flex;gap:4px";c.querySelectorAll("button").forEach(b=>b.style.cssText="width:30px;height:30px;border:1px solid rgba(127,150,184,.25);background:rgba(8,13,21,.9);color:#dce8f7;border-radius:7px;cursor:pointer");c.children[0].onclick=()=>zoom(.8);c.children[1].onclick=()=>zoom(1.25);c.children[2].onclick=fit;body.appendChild(c);svg.addEventListener("wheel",e=>{e.preventDefault();const r=svg.getBoundingClientRect();const p={x:box.x+(e.clientX-r.left)/r.width*box.width,y:box.y+(e.clientY-r.top)/r.height*box.height};zoom(e.deltaY>0?1.1:.9,p.x,p.y)},{passive:false});svg.addEventListener("pointerdown",e=>{if(e.button!==0)return;drag=true;moved=false;last=[e.clientX,e.clientY];svg.setPointerCapture?.(e.pointerId)});svg.addEventListener("pointermove",e=>{const target=e.target.closest?.(".studio-ward,.studio-marker");if(!drag){if(target){tooltip(win,e,target.dataset.zoneId);target.classList.add("hovered")}return;}const r=svg.getBoundingClientRect(),dx=e.clientX-last[0],dy=e.clientY-last[1];if(Math.abs(dx)+Math.abs(dy)>3)moved=true;box.x-=dx/r.width*box.width;box.y-=dy/r.height*box.height;last=[e.clientX,e.clientY];svg.setAttribute("viewBox",`${box.x} ${box.y} ${box.width} ${box.height}`)});svg.addEventListener("pointerup",e=>{drag=false;svg.releasePointerCapture?.(e.pointerId)});svg.addEventListener("pointerleave",()=>{win.querySelectorAll(".hovered").forEach(n=>n.classList.remove("hovered"));const t=win.querySelector(".map-v-final-tooltip");if(t)t.hidden=true});svg.addEventListener("click",e=>{if(moved){moved=false;return}const n=e.target.closest?.(".studio-ward,.studio-marker");if(n&&typeof selectDashboardZone==="function")selectDashboardZone(n.dataset.zoneId)});fit();}
  function create(type){if(state.windows.has(type)){const w=state.windows.get(type);w.style.zIndex=++state.z;return w;}const h=host(),spec=TYPES[type],el=document.createElement("section");el.className="map-studio-window";const off=(state.nextOffset++%4)*30;el.style.left=`${40+off}px`;el.style.top=`${84+off}px`;el.style.zIndex=++state.z;el.innerHTML=`<header class="map-studio-window-head"><div><span class="map-studio-kicker">${esc(spec.kicker)}</span><strong>${esc(spec.title)}</strong><small>${esc(spec.description)}</small></div><button class="map-studio-close" type="button">×</button></header><div class="map-studio-body"><div class="map-studio-loading">Preparing live Chennai view…</div><div class="map-studio-legend">${spec.legend.map(x=>`<span><i class="${esc(x[0])}"></i>${esc(x[1])}</span>`).join("")}</div></div>`;h.appendChild(el);state.windows.set(type,el);el.querySelector(".map-studio-close").onclick=()=>{el.remove();state.windows.delete(type)};dragHead(el);hydrate(el,type);return el;}
  async function hydrate(el,type){const body=el.querySelector(".map-studio-body");for(let i=0;i<100;i++){const d=data();if(d){const svg=makeSvg(type,d);if(svg){const legend=body.querySelector(".map-studio-legend");body.replaceChildren(svg);body.appendChild(legend);bind(el);return;}}await new Promise(r=>setTimeout(r,100));}body.innerHTML=`<div class="map-studio-error"><div><strong>Chennai geography is unavailable.</strong><br><span>Dashboard data did not become available.</span><br><button type="button">Retry</button></div></div>`;body.querySelector("button").onclick=()=>{body.innerHTML=`<div class="map-studio-loading">Preparing live Chennai view…</div>`;hydrate(el,type)};}
  function dragHead(el){const h=el.querySelector(".map-studio-window-head");let drag=false,sx=0,sy=0,ox=0,oy=0;h.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;drag=true;sx=e.clientX;sy=e.clientY;const a=el.getBoundingClientRect(),p=host().getBoundingClientRect();ox=a.left-p.left;oy=a.top-p.top;h.setPointerCapture?.(e.pointerId)});h.addEventListener("pointermove",e=>{if(!drag)return;const p=host().getBoundingClientRect();el.style.left=Math.max(8,Math.min(p.width-el.offsetWidth-8,ox+e.clientX-sx))+"px";el.style.top=Math.max(76,Math.min(p.height-el.offsetHeight-8,oy+e.clientY-sy))+"px"});h.addEventListener("pointerup",()=>drag=false);}
  function open(type){const h=host();h.hidden=false;create(type);}
  function close(){const h=document.querySelector(".map-studio-host");if(h)h.hidden=true;state.windows.forEach(w=>w.remove());state.windows.clear();state.nextOffset=0;}
  function tile(){const h=host(),ws=[...state.windows.values()];if(!ws.length)return;const cols=ws.length<3?ws.length:2,g=14,w=Math.max(320,(h.clientWidth-g*(cols+1))/cols),rows=Math.ceil(ws.length/cols),ht=Math.max(260,(h.clientHeight-100-g*(rows+1))/rows);ws.forEach((x,i)=>{const r=Math.floor(i/cols),c=i%cols;x.style.left=g+c*(w+g)+"px";x.style.top=86+r*(ht+g)+"px";x.style.width=w+"px";x.style.height=ht+"px";});}
  function stack(){const h=host();[...state.windows.values()].forEach((x,i)=>{x.style.width="min(760px,calc(100vw - 80px))";x.style.height="min(560px,calc(100vh - 140px))";x.style.left=40+i*22+"px";x.style.top=86+i*22+"px";x.style.zIndex=++state.z});}
  function launcher(){const header=document.querySelector(".map-panel .panel-header");if(!header||header.querySelector(".map-insight-launcher-final"))return;const b=document.createElement("button");b.className="map-insight-launcher-enhanced map-insight-launcher-final";b.type="button";b.innerHTML="MAP STUDIO <b>↗</b>";b.onclick=()=>open("risk");header.appendChild(b);}
  function boot(){ensureStyle();launcher();}
  window.openMapStudio=open;window.refreshMapStudio=()=>{};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
