(function(){
"use strict";
const TYPES=["risk","flood","access","network","response"];
const TITLES={risk:"Risk Heatmap",flood:"Flood Exposure",access:"Accessibility",network:"Road Network",response:"Response Focus"};
const state={z:200};
function esc(v){return typeof escapeHTML==="function"?escapeHTML(String(v)):String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;")}
function selected(){return typeof selectedZoneId!=="undefined"?selectedZoneId:null}
function level(a){return String(a?.risk_level||"normal").toLowerCase()}
function factor(a,k,d=0){const n=Number(a?.factors?.[k]);return Number.isFinite(n)?n:d}
function cls(type,a){if(type==="risk")return level(a);if(type==="flood"){const w=factor(a,"water_depth_m",factor(a,"water")),r=factor(a,"rainfall_mm_per_hr",factor(a,"rainfall"));return w>=2||r>=100?"critical":w>=1||r>=50?"high":w>0||r>0?"watch":"low"}if(type==="access"){const x=factor(a,"accessibility_percent",100);return x<35?"critical":x<70?"watch":"good"}if(type==="response")return ["critical","high"].includes(level(a))?"critical":level(a)==="watch"?"watch":"good";return"good"}
function sync(el){const type=el.dataset.mapType;const map=typeof realDashboardAssessments!=="undefined"?realDashboardAssessments:new Map();el.querySelectorAll(".studio-ward[data-zone-id],.studio-marker[data-zone-id]").forEach(n=>{const c=cls(type,map.get(n.dataset.zoneId));n.classList.remove("normal","low","watch","high","critical","good","selected");n.classList.add(c);if(n.dataset.zoneId===selected())n.classList.add("selected")})}
function popout(el){const svg=el.querySelector(".map-studio-svg")?.outerHTML;if(!svg)return;const type=el.dataset.mapType;const w=window.open("","map-"+type,"width=1280,height=860,resizable=yes,scrollbars=yes");if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(TITLES[type]||"Map")} · Chennai</title><style>*{box-sizing:border-box}body{margin:0;background:#070b11;color:#edf5ff;font:14px Segoe UI,Arial,sans-serif}.p{padding:22px}.h{display:flex;justify-content:space-between;padding:16px 18px;border:1px solid #27384d;border-radius:14px;background:#0c121c}.h b{color:#ffb21d;letter-spacing:.16em;font-size:10px}.h h1{margin:5px 0;font-size:25px}.h p{margin:0;color:#8197b5}.m{height:calc(100vh - 125px);margin-top:16px;border:1px solid #1e2b3b;border-radius:14px;background:#0b1119;overflow:hidden}.m svg{width:100%;height:100%}button{background:#101a26;color:#dce8f7;border:1px solid #34455b;border-radius:8px;padding:8px 12px;cursor:pointer}</style></head><body><main class="p"><header class="h"><div><b>LIVE MAP VIEW</b><h1>${esc(TITLES[type]||"Map")}</h1><p>Detached map view from the Chennai disaster dashboard.</p></div><button onclick="window.close()">Close</button></header><section class="m">${svg}</section></main></body></html>`);w.document.close();w.focus()}
function path(coords,project){if(!Array.isArray(coords)||coords.length<2)return"";return coords.map((p,i)=>{const q=project(p[0],p[1]);return`${i?"L":"M"}${q[0].toFixed(2)} ${q[1].toFixed(2)}`}).join(" ")}
function polygon(g,project){if(!g)return"";const poly=r=>Array.isArray(r)?r.map(x=>{const d=path(x,project);return d?d+" Z":""}).filter(Boolean).join(" "):"";return g.type==="Polygon"?poly(g.coordinates):g.type==="MultiPolygon"?g.coordinates.map(poly).filter(Boolean).join(" "):""}
function points(v,out){if(!Array.isArray(v))return;if(v.length>=2&&Number.isFinite(Number(v[0]))&&Number.isFinite(Number(v[1]))){out.push([Number(v[0]),Number(v[1])]);return}v.forEach(x=>points(x,out))}
function centroid(g,project){const p=[];points(g?.coordinates,p);if(!p.length)return null;return project(p.reduce((s,x)=>s+x[0],0)/p.length,p.reduce((s,x)=>s+x[1],0)/p.length)}
function optimize(el){
if(el.dataset.optimized)return;
const d=window.realDashboardGeoCache;if(!d?.wards?.length||!d?.roads?.length)return;
const pts=[];d.roads.forEach(r=>(r.path||[]).forEach(p=>Array.isArray(p)&&p.length>=2&&pts.push([+p[0],+p[1]])));if(!pts.length)return;
const minX=Math.min(...pts.map(p=>p[0])),maxX=Math.max(...pts.map(p=>p[0])),minY=Math.min(...pts.map(p=>p[1])),maxY=Math.max(...pts.map(p=>p[1])),W=1000,H=620,P=34,sx=Math.max(maxX-minX,1e-6),sy=Math.max(maxY-minY,1e-6),scale=Math.min((W-P*2)/sx,(H-P*2)/sy),ox=(W-sx*scale)/2,oy=(H-sy*scale)/2,project=(lon,lat)=>[ox+(+lon-minX)*scale,H-(oy+(+lat-minY)*scale)];
const A=typeof realDashboardAssessments!=="undefined"?realDashboardAssessments:new Map(),wards=[],roads={open:[],restricted:[],blocked:[]},links={open:[],restricted:[],blocked:[]};
d.wards.forEach(w=>{const raw=w?.properties?.ward_id??w?.properties?.ward,id=raw==null?null:"W"+raw,dd=polygon(w.geometry,project),c=centroid(w.geometry,project);if(id&&dd&&c)wards.push({id,d:dd,c})});
const cm=new Map(wards.map(w=>[w.id,w.c])),pairs=new Set();
d.roads.forEach(r=>{const dd=path(r.path,project);if(!dd)return;const s=r.blocked?"blocked":Number(r.accessibility_percent??100)<70?"restricted":"open";roads[s].push(dd);if(cm.has(r.from_zone_id)&&cm.has(r.to_zone_id)){const k=[r.from_zone_id,r.to_zone_id].sort().join("|");if(!pairs.has(k)){pairs.add(k);const a=cm.get(r.from_zone_id),b=cm.get(r.to_zone_id);links[s].push("M"+a[0].toFixed(2)+" "+a[1].toFixed(2)+" L"+b[0].toFixed(2)+" "+b[1].toFixed(2))}}});
const type=el.dataset.mapType;
const wardMarkup=wards.map(w=>{const c=cls(type,A.get(w.id));return '<path class="studio-ward '+c+(w.id===selected()?" selected":"")+'" data-zone-id="'+esc(w.id)+'" d="'+w.d+'"/>'}).join("");
const markerMarkup=wards.map(w=>{const c=cls(type,A.get(w.id));return '<circle class="studio-marker '+c+(w.id===selected()?" selected":"")+'" data-zone-id="'+esc(w.id)+'" cx="'+w.c[0].toFixed(2)+'" cy="'+w.c[1].toFixed(2)+'" r="3.4"/>'}).join("");
const linkMarkup=Object.entries(links).map(([c,v])=>v.length?'<path class="studio-zone-link '+c+'" d="'+v.join(" ")+'"/>':"").join("");
const roadMarkup=Object.entries(roads).map(([c,v])=>v.length?'<path class="studio-road '+c+'" d="'+v.join(" ")+'"/>':"").join("");
const svg='<svg class="map-studio-svg optimized" viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="xMidYMid meet"><g class="studio-ward-layer">'+wardMarkup+'</g><g class="studio-zone-links">'+linkMarkup+'</g><g class="studio-road-layer">'+roadMarkup+'</g><g class="studio-marker-layer">'+markerMarkup+'</g></svg>';
const legend=el.querySelector(".map-studio-legend")?.outerHTML||"";
el.querySelector(".map-studio-body").innerHTML=svg+'<div class="map-studio-mapbar"><span class="map-studio-live"><i></i> LIVE GEOGRAPHY</span><span>Click a ward to inspect</span><span>Roads: '+d.roads.length.toLocaleString()+'</span></div>'+legend;
el.dataset.optimized="1";
const s=el.querySelector(".map-studio-svg");s?.addEventListener("click",e=>{const w=e.target.closest(".studio-ward");if(!w)return;if(typeof selectDashboardZone==="function")selectDashboardZone(w.dataset.zoneId);sync(el)});
}
function addActions(el){if(el.querySelector(".map-studio-enhanced-actions"))return;const head=el.querySelector(".map-studio-window-head");if(!head)return;const box=document.createElement("div");box.className="map-studio-enhanced-actions";box.innerHTML='<button type="button" data-enhance="popout" title="Open separate map window">↗</button><button type="button" data-enhance="maximize" title="Maximize">□</button>';head.appendChild(box);box.querySelector('[data-enhance="popout"]').onclick=e=>{e.stopPropagation();popout(el)};box.querySelector('[data-enhance="maximize"]').onclick=e=>{e.stopPropagation();el.classList.toggle("enhanced-max");if(el.classList.contains("enhanced-max")){el.style.left="24px";el.style.top="88px";el.style.width="calc(100vw - 48px)";el.style.height="calc(100vh - 112px)";el.style.zIndex=++state.z}else{el.style.width="760px";el.style.height="620px"}}}
function addTile(host){const top=host.querySelector(".map-studio-topbar");if(!top||top.querySelector(".enhanced-tile"))return;const b=document.createElement("button");b.className="enhanced-tile";b.type="button";b.textContent="Tile maps";b.onclick=()=>tile(host);top.querySelector("div:last-child")?.prepend(b)}
function tile(host){const maps=[...host.querySelectorAll(".map-studio-window")];if(!maps.length)return;const c=host.getBoundingClientRect(),gap=18,cols=maps.length<=4?2:3,rows=Math.ceil(maps.length/cols),w=Math.max(380,(c.width-gap*(cols+1))/cols),h=Math.max(380,(c.height-110-gap*(rows+1))/rows);maps.forEach((el,i)=>{const x=i%cols,y=Math.floor(i/cols);el.classList.remove("enhanced-max");el.style.left=`${gap+x*(w+gap)}px`;el.style.top=`${90+y*(h+gap)}px`;el.style.width=`${Math.min(760,w)}px`;el.style.height=`${Math.min(620,h)}px`;el.style.zIndex=++state.z})}
function launcher(){const h=document.querySelector(".map-panel .panel-header");if(!h||h.querySelector(".map-insight-launcher-enhanced"))return;const b=document.createElement("button");b.className="map-insight-launcher-enhanced";b.type="button";b.innerHTML="▣ MAP INSIGHTS <b>↗</b>";b.onclick=()=>{if(typeof openMapStudio==="function")openMapStudio();else document.querySelector(".map-insight-toolbar button")?.click()};h.appendChild(b)}
function styles(){if(document.getElementById("map-studio-enhanced-css"))return;const s=document.createElement("style");s.id="map-studio-enhanced-css";s.textContent=`.map-insight-launcher-enhanced{margin-left:auto;display:inline-flex;align-items:center;gap:8px;border:1px solid rgba(255,178,29,.34);border-radius:9px;background:rgba(255,178,29,.07);color:#dce8f7;padding:8px 11px;font:800 9px/1 inherit;letter-spacing:.08em;cursor:pointer;white-space:nowrap}.map-insight-launcher-enhanced:hover{border-color:rgba(255,178,29,.7);background:rgba(255,178,29,.13)}.map-studio-window{width:min(760px,calc(100vw - 70px))!important;height:min(620px,calc(100vh - 130px))!important}.map-studio-window-head>.map-studio-close{display:none}.map-studio-enhanced-actions{display:flex;gap:5px;margin-left:auto}.map-studio-enhanced-actions button{width:30px;height:28px;border:1px solid rgba(127,150,184,.23);background:rgba(255,255,255,.035);color:#b9c9dd;border-radius:8px;cursor:pointer;font-weight:800}.map-studio-enhanced-actions button:hover{border-color:rgba(75,166,255,.55);background:rgba(75,166,255,.1);color:#fff}.map-studio-window.enhanced-max{width:calc(100vw - 48px)!important;height:calc(100vh - 112px)!important}.map-studio-svg.optimized{height:100%;min-height:0}.map-studio-host .map-studio-window{will-change:left,top}.map-studio-host .map-studio-topbar>div:last-child{display:flex;gap:7px;align-items:center}.map-studio-host .enhanced-tile{border:1px solid rgba(127,150,184,.23);background:rgba(255,255,255,.035);color:#b9c9dd;border-radius:8px;padding:8px 11px;font-size:10px;font-weight:800;cursor:pointer}`;document.head.appendChild(s)}
function observe(){styles();launcher();const obs=new MutationObserver(()=>{launcher();const host=document.querySelector(".map-studio-host");if(!host)return;addTile(host);host.querySelectorAll(".map-studio-window").forEach(el=>{optimize(el);addActions(el);sync(el)})});obs.observe(document.body,{childList:true,subtree:true});document.addEventListener("click",e=>{const n=e.target.closest?.(".nav-item");if(n)setTimeout(()=>{launcher();window.dispatchEvent(new Event("resize"))},100);if(e.target.closest?.(".studio-ward")){const ward=e.target.closest(".studio-ward");if(typeof selectDashboardZone==="function"){e.preventDefault();e.stopImmediatePropagation();selectDashboardZone(ward.dataset.zoneId);sync(e.target.closest(".map-studio-window"))}}},{capture:true});window.addEventListener("resize",()=>{document.querySelectorAll(".map-studio-window").forEach(sync)})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",observe,{once:true});else observe();
})();
