(function(){
  "use strict";
  function esc(v){return typeof escapeHTML==="function"?escapeHTML(String(v)):String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
  function assessments(){return typeof DASHBOARD_RUNTIME!=="undefined"&&DASHBOARD_RUNTIME.assessments instanceof Map?DASHBOARD_RUNTIME.assessments:(window.realDashboardAssessments instanceof Map?window.realDashboardAssessments:new Map());}
  function level(a){return String(a?.risk_level||"normal").toLowerCase();}
  function factor(a,...keys){for(const k of keys){const n=Number(a?.factors?.[k]);if(Number.isFinite(n))return n;}return 0;}
  function tooltip(area,e,id){const a=assessments().get(id);if(!a)return;let t=area.querySelector(".dashboard-zone-tooltip");if(!t){t=document.createElement("div");t.className="dashboard-zone-tooltip";area.appendChild(t);}const w=factor(a,"water_depth_m","water"),r=factor(a,"rainfall_mm_per_hr","rainfall"),ac=a.factors?.accessibility_percent!=null?Number(a.factors.accessibility_percent):Math.max(0,100-factor(a,"accessibility_risk"));t.innerHTML=`<b>${esc(id)} · ${esc(level(a).toUpperCase())}</b><span>Risk ${Number(a.risk_score??0).toFixed(2)} / 100</span><strong>Water ${w.toFixed(2)} m · Rain ${r.toFixed(0)} mm/hr · Access ${ac.toFixed(0)}%</strong>`;const ar=area.getBoundingClientRect();let x=e.clientX-ar.left+12,y=e.clientY-ar.top+12;x=Math.min(Math.max(8,x),Math.max(8,ar.width-t.offsetWidth-8));y=Math.min(Math.max(8,y),Math.max(8,ar.height-t.offsetHeight-8));t.style.left=x+"px";t.style.top=y+"px";t.hidden=false;}
  function enhance(){const area=document.querySelector(".map-area"),svg=area?.querySelector("svg.real-chennai-map");if(!area||!svg)return;let layer=svg.querySelector(".main-zone-markers");if(!layer){layer=document.createElementNS("http://www.w3.org/2000/svg","g");layer.classList.add("main-zone-markers");svg.appendChild(layer);}const count=svg.querySelectorAll(".real-ward").length;if(layer.dataset.version===String(count))return;layer.replaceChildren();const as=assessments();svg.querySelectorAll(".real-ward").forEach(ward=>{const id=ward.dataset.zoneId;if(!id)return;let box;try{box=ward.getBBox();}catch{return;}if(!box.width&&!box.height)return;const a=as.get(id),c=document.createElementNS("http://www.w3.org/2000/svg","circle");c.classList.add("main-zone-marker",level(a));c.dataset.zoneId=id;c.setAttribute("cx",(box.x+box.width/2).toFixed(2));c.setAttribute("cy",(box.y+box.height/2).toFixed(2));c.setAttribute("r","3.2");c.setAttribute("vector-effect","non-scaling-stroke");const title=document.createElementNS("http://www.w3.org/2000/svg","title");const w=factor(a,"water_depth_m","water"),r=factor(a,"rainfall_mm_per_hr","rainfall"),ac=a?.factors?.accessibility_percent!=null?Number(a.factors.accessibility_percent):Math.max(0,100-factor(a,"accessibility_risk"));title.textContent=`${id} · ${level(a).toUpperCase()} · Risk ${Number(a?.risk_score??0).toFixed(2)}/100 · Water ${w.toFixed(2)} m · Rain ${r.toFixed(0)} mm/hr · Access ${ac.toFixed(0)}%`;c.appendChild(title);layer.appendChild(c);});layer.dataset.version=String(count);layer.style.pointerEvents="none";svg.querySelectorAll(".real-ward").forEach(ward=>{if(ward.dataset.zoneTooltipBound)return;ward.dataset.zoneTooltipBound="1";ward.addEventListener("pointerenter",e=>tooltip(area,e,ward.dataset.zoneId));ward.addEventListener("pointermove",e=>tooltip(area,e,ward.dataset.zoneId));ward.addEventListener("pointerleave",()=>{const t=area.querySelector(".dashboard-zone-tooltip");if(t)t.hidden=true;});});}
  function style(){if(document.getElementById("dashboard-zone-marker-style"))return;const s=document.createElement("style");s.id="dashboard-zone-marker-style";s.textContent=`.main-zone-markers{pointer-events:none}.main-zone-marker{fill:#35d07f;stroke:#08101a;stroke-width:.9;filter:drop-shadow(0 0 3px rgba(53,208,127,.55))}.main-zone-marker.watch{fill:#ffb738}.main-zone-marker.high{fill:#ff7d48}.main-zone-marker.critical{fill:#ff4c60}.dashboard-zone-tooltip{position:absolute;z-index:80;min-width:205px;max-width:260px;padding:10px 11px;border:1px solid rgba(83,113,153,.45);border-radius:10px;background:rgba(7,12,20,.97);box-shadow:0 14px 34px rgba(0,0,0,.45);pointer-events:none;color:#dce8f7}.dashboard-zone-tooltip b{display:block;color:#fff;font-size:12px}.dashboard-zone-tooltip span{display:block;color:#8fa5c0;font-size:10px;margin-top:3px}.dashboard-zone-tooltip strong{display:block;color:#35d07f;font-size:10px;margin-top:8px}`;document.head.appendChild(s);}
  function boot(){style();enhance();const area=document.querySelector(".map-area");if(area&&!area.dataset.markerObserver){area.dataset.markerObserver="1";new MutationObserver(()=>requestAnimationFrame(enhance)).observe(area,{childList:true,subtree:true});}setTimeout(enhance,250);setTimeout(enhance,1000);}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
