(function(){
"use strict";
const state={svg:null,box:null,drag:false,lastX:0,lastY:0,moved:false};
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function fit(){if(!state.svg)return;const layers=[...state.svg.querySelectorAll(".real-ward-layer,.real-road-layer")];let b=null;layers.forEach(l=>{try{const x=l.getBBox();if(!x.width||!x.height)return;if(!b)b={x:x.x,y:x.y,width:x.width,height:x.height};else{const r=Math.max(b.x+b.width,x.x+x.width),d=Math.max(b.y+b.height,x.y+x.height);b.x=Math.min(b.x,x.x);b.y=Math.min(b.y,x.y);b.width=r-b.x;b.height=d-b.y}}catch{}});if(!b)return;const px=Math.max(10,b.width*.07),py=Math.max(10,b.height*.08);setBox({x:b.x-px,y:b.y-py,width:b.width+px*2,height:b.height+py*2})}
function setBox(b){state.box=b;state.svg?.setAttribute("viewBox",`${b.x} ${b.y} ${b.width} ${b.height}`)}
function point(x,y){const r=state.svg.getBoundingClientRect(),b=state.box;return{x:b.x+(x-r.left)/r.width*b.width,y:b.y+(y-r.top)/r.height*b.height}}
function zoom(f,x,y){if(!state.svg||!state.box)return;const b=state.box,w=clamp(b.width*f,40,900),h=clamp(b.height*f,30,330),rx=x==null?.5:clamp((x-b.x)/b.width,0,1),ry=y==null?.5:clamp((y-b.y)/b.height,0,1);setBox({x:x==null?b.x+(b.width-w)/2:x-w*rx,y:y==null?b.y+(b.height-h)/2:y-h*ry,width:w,height:h})}
function attach(){const host=document.querySelector(".map-area"),svg=host?.querySelector("svg.real-chennai-map");if(!host||!svg||svg.dataset.navigationFixed==="1")return;state.svg=svg;const b=svg.viewBox.baseVal;state.box={x:b.x,y:b.y,width:b.width,height:b.height};svg.dataset.navigationFixed="1";if(!host.querySelector(".map-control-rail")){const rail=document.createElement("div");rail.className="map-control-rail";rail.innerHTML='<button type="button">+</button><button type="button">−</button><button type="button">⌖</button>';host.appendChild(rail);rail.children[0].onclick=()=>zoom(.78);rail.children[1].onclick=()=>zoom(1.28);rail.children[2].onclick=fit;const hint=document.createElement("div");hint.className="map-interaction-hint";hint.innerHTML='<span class="hint-dot"></span> Click a ward · scroll to zoom · drag to pan';host.appendChild(hint)}requestAnimationFrame(fit);svg.addEventListener("wheel",e=>{e.preventDefault();const p=point(e.clientX,e.clientY);zoom(e.deltaY>0?1.12:.89,p.x,p.y)},{passive:false});svg.addEventListener("pointerdown",e=>{if(e.button!==0)return;state.drag=true;state.moved=false;state.lastX=e.clientX;state.lastY=e.clientY;svg.setPointerCapture?.(e.pointerId);svg.classList.add("is-panning")});svg.addEventListener("pointermove",e=>{if(!state.drag)return;const dx=e.clientX-state.lastX,dy=e.clientY-state.lastY;if(Math.abs(dx)+Math.abs(dy)>2)state.moved=true;const r=svg.getBoundingClientRect();setBox({x:state.box.x-dx/r.width*state.box.width,y:state.box.y-dy/r.height*state.box.height,width:state.box.width,height:state.box.height});state.lastX=e.clientX;state.lastY=e.clientY});svg.addEventListener("pointerup",e=>{state.drag=false;svg.classList.remove("is-panning");svg.releasePointerCapture?.(e.pointerId)});svg.addEventListener("pointercancel",()=>{state.drag=false;svg.classList.remove("is-panning")});svg.addEventListener("click",e=>{if(state.moved){state.moved=false;e.preventDefault();e.stopImmediatePropagation();return}const ward=e.target.closest?.(".real-ward");if(ward&&typeof selectDashboardZone==="function")selectDashboardZone(ward.dataset.zoneId)},true)}
function init(){const obs=new MutationObserver(()=>setTimeout(attach,35));obs.observe(document.body,{childList:true,subtree:true});document.addEventListener("click",e=>{if(e.target.closest?.(".nav-item"))setTimeout(attach,100)});document.addEventListener("visibilitychange",()=>{if(!document.hidden)setTimeout(attach,100)});attach()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
