from dataclasses import dataclass


@dataclass(frozen=True)
class ResponseAction:
    """
    Represents an operational action generated by the
    disaster-response decision system.
    """

    zone_id: str
    risk_level: str
    action_type: str
    priority: int
    description: str

    def __post_init__(self):
        if not self.zone_id:
            raise ValueError("zone_id cannot be empty")

        if not self.risk_level:
            raise ValueError("risk_level cannot be empty")

        if not self.action_type:
            raise ValueError("action_type cannot be empty")

        if self.priority < 1:
            raise ValueError("priority must be at least 1")

        if not self.description:
            raise ValueError("description cannot be empty")